env:
  n_other_vessels: 5

train:
  episodes: 10000
  max_steps: 500
  batch_size: 128
  actor_lr: 1.0e-4
  critic_lr: 1.0e-3
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2

logging:
  save_gif_every_ep: 200
  reward_plot_filename: "episode_rewards_td3.png"

eval:
  episodes: 100
  max_steps: 500
  seed: 0
